name: Test Simple Activity Update

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Simple README Update
              run: |
                  # Create a simple activity list with the format you want
                  cat > temp_activity.txt << 'EOF'
                  1. ⬆️ Pushed to MA1002643/vevox-real-time-chat-web-application<br>
                  2. ⬆️ Pushed to MA1002643/article-server-full-stack-blogging-platform<br>
                  3. ⬆️ Pushed to MA1002643/MA1002643<br>
                  4. 📦 Created repository MA1002643/new-project<br>
                  5. ⭐ Starred MA1002643/example-repo<br>
                  EOF

                  # Replace the activity section in README
                  sed -i '/<!--RECENT_ACTIVITY:start-->/,/<!--RECENT_ACTIVITY:end-->/{
                    /<!--RECENT_ACTIVITY:start-->/!{
                      /<!--RECENT_ACTIVITY:end-->/!d
                    }
                  }' README.md

                  # Insert new content
                  sed -i '/<!--RECENT_ACTIVITY:start-->/r temp_activity.txt' README.md

                  # Update timestamp
                  TIMESTAMP=$(date '+%A, %B %d, %Y, %I:%M:%S %p')
                  sed -i "s/Last Updated: .*/Last Updated: $TIMESTAMP/" README.md

                  rm temp_activity.txt

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "docs: update recent activity (simplified)"
                  file_pattern: README.md
